let playableCharacters = [
	(RedMage = new Mage(id++, "Red Mage", "/assets/red-mage.gif")),
	(ChunLi = new Brawler(id++, "Chun-Li", "/assets/chunli.gif")),
	(Mario = new Character(id++, "Mario", "/assets/mario.gif")),
	(Kratos = new Warrior(id++, "Kratos", "/assets/kratos.gif")),
	(Wizard = new Mage(id++, "Wizard", "/assets/wizard.gif")),
	(Goku = new Brawler(id++, "Son Goku", "/assets/goku.gif")),
	(Sonic = new Character(id++, "Sonic", "/assets/sonic.gif")),
	(Cloud = new Warrior(id++, "Cloud", "/assets/cloud.gif")),
	(BookMage = new Mage(id++, "Book Mage", "/assets/book-mage.gif")),
	(Batman = new Brawler(id++, "Batman", "/assets/batman.gif")),
	(Samus = new Character(id++, "Samus", "/assets/samus.gif")),
	(Link = new Warrior(id++, "Link", "/assets/link.gif")),
	(DarkMage = new Mage(id++, "Dark Mage", "/assets/dark-mage.gif")),
	(DonkeyKong = new Brawler(id++, "Donkey Kong", "/assets/donkey-kong.gif")),
	(Pikachu = new Character(id++, "Pikachu", "/assets/pikachu.gif")),
	(Alucard = new Warrior(id++, "Alucard", "/assets/alucard.gif")),
];
